"""add_mendeley_fields

Revision ID: a99844a39edd
Revises: 7ad9edad17b3
Create Date: 2026-06-07 09:49:07.960086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a99844a39edd'
down_revision: Union[str, Sequence[str], None] = '7ad9edad17b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cursos_codigo_key', 'cursos', type_='unique')
    op.drop_constraint('estados_recurso_nombre_key', 'estados_recurso', type_='unique')
    op.drop_index('ix_estados_recurso_nombre', table_name='estados_recurso')
    op.create_index(op.f('ix_estados_recurso_nombre'), 'estados_recurso', ['nombre'], unique=True)
    op.drop_constraint('niveles_dificultad_nombre_key', 'niveles_dificultad', type_='unique')
    op.drop_index('ix_niveles_dificultad_nombre', table_name='niveles_dificultad')
    op.create_index(op.f('ix_niveles_dificultad_nombre'), 'niveles_dificultad', ['nombre'], unique=True)
    op.add_column('recursos', sa.Column('autores', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.add_column('recursos', sa.Column('editorial', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('recursos', sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('recursos', sa.Column('anio', sa.Integer(), nullable=True))
    op.drop_index('ix_recursos_curso_id', table_name='recursos')
    op.drop_index('ix_recursos_estado_id', table_name='recursos')
    op.drop_index('ix_recursos_tipo_recurso_id', table_name='recursos')
    op.drop_constraint('roles_nombre_key', 'roles', type_='unique')
    op.drop_index('ix_roles_nombre', table_name='roles')
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.drop_constraint('tipos_actividad_nombre_key', 'tipos_actividad', type_='unique')
    op.drop_index('ix_tipos_actividad_nombre', table_name='tipos_actividad')
    op.create_index(op.f('ix_tipos_actividad_nombre'), 'tipos_actividad', ['nombre'], unique=True)
    op.drop_constraint('tipos_recurso_nombre_key', 'tipos_recurso', type_='unique')
    op.drop_index('ix_tipos_recurso_nombre', table_name='tipos_recurso')
    op.create_index(op.f('ix_tipos_recurso_nombre'), 'tipos_recurso', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_recurso_nombre'), table_name='tipos_recurso')
    op.create_index('ix_tipos_recurso_nombre', 'tipos_recurso', ['nombre'], unique=False)
    op.create_unique_constraint('tipos_recurso_nombre_key', 'tipos_recurso', ['nombre'])
    op.drop_index(op.f('ix_tipos_actividad_nombre'), table_name='tipos_actividad')
    op.create_index('ix_tipos_actividad_nombre', 'tipos_actividad', ['nombre'], unique=False)
    op.create_unique_constraint('tipos_actividad_nombre_key', 'tipos_actividad', ['nombre'])
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.create_index('ix_roles_nombre', 'roles', ['nombre'], unique=False)
    op.create_unique_constraint('roles_nombre_key', 'roles', ['nombre'])
    op.create_index('ix_recursos_tipo_recurso_id', 'recursos', ['tipo_recurso_id'], unique=False)
    op.create_index('ix_recursos_estado_id', 'recursos', ['estado_id'], unique=False)
    op.create_index('ix_recursos_curso_id', 'recursos', ['curso_id'], unique=False)
    op.drop_column('recursos', 'anio')
    op.drop_column('recursos', 'doi')
    op.drop_column('recursos', 'editorial')
    op.drop_column('recursos', 'autores')
    op.drop_index(op.f('ix_niveles_dificultad_nombre'), table_name='niveles_dificultad')
    op.create_index('ix_niveles_dificultad_nombre', 'niveles_dificultad', ['nombre'], unique=False)
    op.create_unique_constraint('niveles_dificultad_nombre_key', 'niveles_dificultad', ['nombre'])
    op.drop_index(op.f('ix_estados_recurso_nombre'), table_name='estados_recurso')
    op.create_index('ix_estados_recurso_nombre', 'estados_recurso', ['nombre'], unique=False)
    op.create_unique_constraint('estados_recurso_nombre_key', 'estados_recurso', ['nombre'])
    op.create_unique_constraint('cursos_codigo_key', 'cursos', ['codigo'])
    # ### end Alembic commands ###
