FROM postgres:15-bullseye

RUN apt-get update -y \
    && apt-get install -y python3 python3-pip python3-dev libpq-dev curl \
    && (pip3 install patroni[etcd3] psycopg2-binary --break-system-packages || pip3 install patroni[etcd3] psycopg2-binary)

# Asegurar permisos correctos
RUN mkdir -p /home/postgres/pgdata && chown -R postgres:postgres /home/postgres

USER postgres
ENV PATH="/usr/lib/postgresql/15/bin:$PATH"

CMD ["patroni", "/patroni.yml"]
