scope: fiq-postgres
namespace: /service/

restapi:
  listen: 0.0.0.0:8008

etcd:
  hosts: 127.0.0.1:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_size: 512MB
        max_wal_senders: 10
        max_replication_slots: 10
        checkpoint_timeout: 60s
        max_connections: 200
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator all md5
    - host all postgres all md5
    - host all all all md5

  users:
    replicator:
      options:
        - replication
    rewind_user:
      options:
        - superuser

postgresql:
  listen: 0.0.0.0:5432
  data_dir: /home/postgres/pgdata/data
  bin_dir: /usr/lib/postgresql/17/bin
  pgpass: /tmp/pgpass
  authentication:
    superuser:
      username: postgres
    replication:
      username: replicator
    rewind:
      username: rewind_user
  parameters:
    unix_socket_directories: '.'
    shared_buffers: 256MB
    effective_cache_size: 768MB
    maintenance_work_mem: 64MB
    log_min_duration_statement: 1000
    log_connections: "on"
    log_disconnections: "on"
